twig:
    default_path: '%kernel.project_dir%/templates'
    strict_variables: true
    globals:
        flash: '@Hiberus\Skeleton\Shared\Infrastructure\Symfony\FlashSession'

when@test:
    twig:
        strict_variables: true
