user_put:
  path: /user/{id}
  controller: Hiberus\Skeleton\App\Controller\Registration\UserPutController
  defaults: { auth: false }
  methods: PUT

ticket_put:
  path: /ticket/{id}
  controller: Hiberus\Skeleton\App\Controller\Ticket\TicketPutController
  defaults: { auth: false }
  methods: PUT
