#FROM php:8.1-rc-apache
FROM php:8.1-apache

# PHP
RUN apt-get update && \
    apt-get install -y --no-install-recommends libssl-dev zlib1g-dev curl git unzip netcat libxml2-dev libpq-dev libzip-dev ssh-client supervisor && \
    pecl install apcu xdebug-3.1.1 redis-5.3.4 && \
    docker-php-ext-install -j$(nproc) zip opcache intl pdo_mysql sockets && \
    docker-php-ext-enable apcu sodium && \
    docker-php-ext-enable redis && \
    docker-php-ext-enable xdebug && \
    echo "xdebug.mode=develop,debug" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "xdebug.client_host=host.docker.internal" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Supervisor
COPY docker/supervisor/supervisord.conf /etc/supervisor
COPY docker/supervisor/config/* /etc/supervisor/conf.d/

# Apache
COPY docker/vhost.conf /etc/apache2/sites-available
RUN a2enmod rewrite && \
    a2dissite 000-default && \
    a2ensite vhost && \
    service apache2 restart

# Install symfony
RUN curl -sS https://get.symfony.com/cli/installer | bash \
    && mv ~/.symfony5/bin/symfony /usr/local/bin/symfony

WORKDIR /var/www

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]