services:
  PhpAmqpLib\Connection\AMQPStreamConnection:
    arguments:
      $host: '%env(RABBITMQ_HOST)%'
      $port: '%env(RABBITMQ_PORT)%'
      $user: '%env(RABBITMQ_USER)%'
      $password: '%env(RABBITMQ_PASSWORD)%'
      $vhost: '%env(RABBITMQ_VHOST)%'

  PhpAmqpLib\Connection\AbstractConnection: '@PhpAmqpLib\Connection\AMQPStreamConnection'

  Hiberus\Skeleton\Tests\Fixtures\InitialDataFixtures:
    tags:
      - { name: dotrine.fixture.orm }